apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      targetRevision: "0.113.0"
      helm:
        releaseName: opentelemetry-collector
        valueFiles:
          - $values/platform/addons/qa/opentelemetry-collector/values.yaml
    - repoURL: https://github.com/saitama0333/eks-platform-demo.git
      targetRevision: develop
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true




