apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-platform-addons
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saitama0333/eks-platform-demo.git
    targetRevision: develop
    path: platform
    directory:
      recurse: true
      include: '{addons/dev/**/application.yaml,apps/dev/**/application.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true