grafana:
  enabled: true
  additionalDataSources:
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo.monitoring.svc.cluster.local:3100
      isDefault: false
prometheus:
  prometheusSpec:
    retention: 7d
alertmanager:
  enabled: true
