apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saitama0333/eks-platform-demo.git
    targetRevision: develop
    path: platform/karpenter/qa
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
