apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-gp3
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://github.com/saitama0333/eks-platform-demo.git
    targetRevision: develop
    path: platform/storage
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
